from typing import Final

from .base import ModelSettingDict


# Qwen models
QWEN_DEFAULT_MODEL: Final[str] = "qwen3.5-397b-a17b"
QWEN_MODELS: Final[dict[str, ModelSettingDict]] = {
    "qwen2.5-7b-instruct": {
        "id": "qwen2.5-7b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen2.5-14b-instruct": {
        "id": "qwen2.5-14b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen2.5-32b-instruct": {
        "id": "qwen2.5-32b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen2.5-coder-32b-instruct": {
        "id": "qwen2.5-coder-32b-instruct",
        "context_length": 30000,
        "max_output_tokens": 4096,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": False,
    },
    "qwq-32b": {
        "id": "qwq-32b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": False,
    },
    "qwen2.5-72b-instruct": {
        "id": "qwen2.5-72b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen2-vl-72b-instruct": {
        "id": "qwen2-vl-72b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen2.5-vl-72b-instruct": {
        "id": "qwen2.5-vl-72b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen2.5-vl-7b-instruct": {
        "id": "qwen2.5-vl-7b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen2.5-vl-3b-instruct": {
        "id": "qwen2.5-vl-3b-instruct",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen-max": {
        "id": "qwen-max",
        "context_length": 8096,
        "max_output_tokens": 2048,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen-max-longcontext": {
        "id": "qwen-max-longcontext",
        "context_length": 30000,
        "max_output_tokens": 2048,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen-plus": {
        "id": "qwen-plus",
        "context_length": 131072,
        "max_output_tokens": 8096,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen-turbo": {
        "id": "qwen-turbo",
        "context_length": 8096,
        "max_output_tokens": 1500,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qvq-max": {
        "id": "qvq-max",
        "context_length": 122880,
        "max_output_tokens": 8192,
        "function_call_available": False,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-235b-a22b": {
        "id": "qwen3-235b-a22b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-32b": {
        "id": "qwen3-32b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-30b-a3b": {
        "id": "qwen3-30b-a3b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-14b": {
        "id": "qwen3-14b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-8b": {
        "id": "qwen3-8b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-4b": {
        "id": "qwen3-4b",
        "context_length": 131072,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-1.7b": {
        "id": "qwen3-1.7b",
        "context_length": 32768,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-0.6b": {
        "id": "qwen3-0.6b",
        "context_length": 32768,
        "max_output_tokens": 8192,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-235b-a22b-instruct-2507": {
        "id": "qwen3-235b-a22b-instruct-2507",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-235b-a22b-thinking-2507": {
        "id": "qwen3-235b-a22b-thinking-2507",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-coder-480b-a35b-instruct": {
        "id": "qwen3-coder-480b-a35b-instruct",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-next-80b-a3b-thinking": {
        "id": "qwen3-next-80b-a3b-thinking",
        "context_length": 159744,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-next-80b-a3b-instruct": {
        "id": "qwen3-next-80b-a3b-instruct",
        "context_length": 159744,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-max-preview": {
        "id": "qwen3-max-preview",
        "context_length": 262144,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-max": {
        "id": "qwen3-max",
        "context_length": 262144,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-vl-plus": {
        "id": "qwen3-vl-plus",
        "context_length": 262144,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-coder-plus": {
        "id": "qwen3-coder-plus",
        "context_length": 1000000,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-coder-flash": {
        "id": "qwen3-coder-flash",
        "context_length": 1000000,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
    "qwen3-vl-235b-a22b-thinking": {
        "id": "qwen3-vl-235b-a22b-thinking",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-235b-a22b-instruct": {
        "id": "qwen3-vl-235b-a22b-instruct",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-30b-a3b-thinking": {
        "id": "qwen3-vl-30b-a3b-thinking",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-30b-a3b-instruct": {
        "id": "qwen3-vl-30b-a3b-instruct",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-8b-thinking": {
        "id": "qwen3-vl-8b-thinking",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-8b-instruct": {
        "id": "qwen3-vl-8b-instruct",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-flash": {
        "id": "qwen3-vl-flash",
        "context_length": 262144,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-32b-thinking": {
        "id": "qwen3-vl-32b-thinking",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3-vl-32b-instruct": {
        "id": "qwen3-vl-32b-instruct",
        "context_length": 131072,
        "max_output_tokens": 32768,
        "function_call_available": True,
        "response_format_available": False,
        "native_multimodal": True,
    },
    "qwen3.5-397b-a17b": {
        "id": "qwen3.5-397b-a17b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-122b-a10b": {
        "id": "qwen3.5-122b-a10b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-27b": {
        "id": "qwen3.5-27b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-35b-a3b": {
        "id": "qwen3.5-35b-a3b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-9b": {
        "id": "qwen3.5-9b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-4b": {
        "id": "qwen3.5-4b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-2b": {
        "id": "qwen3.5-2b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.5-0.8b": {
        "id": "qwen3.5-0.8b",
        "context_length": 262144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.6-plus": {
        "id": "qwen3.6-plus",
        "context_length": 1_000_000,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.6-flash": {
        "id": "qwen3.6-flash",
        "context_length": 1_000_000,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.6-35b-a3b": {
        "id": "qwen3.6-35b-a3b",
        "context_length": 262_144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.6-27b": {
        "id": "qwen3.6-27b",
        "context_length": 262_144,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": True,
    },
    "qwen3.7-max": {
        "id": "qwen3.7-max",
        "context_length": 1_000_000,
        "max_output_tokens": 65536,
        "function_call_available": True,
        "response_format_available": True,
        "native_multimodal": False,
    },
}
